version: '3.6'
services:
  app:
    image: 904777360972.dkr.ecr.us-east-1.amazonaws.com/
    #ports:
    #  - 8089:80
    env_file: 
      - general.env
      - environment.env
    deploy:
      placement:
        constraints:
         - node.platform.os == linux
    healthcheck:
      test: curl --fail -s http://localhost/healthcheck || exit 1
      interval: 20s
      timeout: 10s
      retries: 3
    expose:
      - 80
    networks:
      - network
networks:
  network:
